# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 09:41
from __future__ import unicode_literals

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=company.models.company_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CO', 'Computer Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('CH', 'Chemical Engineering'), ('EC', 'Electronics and Communication Engineering'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematics'), ('ALL', 'All Branches')], max_length=4)),
                ('degree', models.CharField(choices=[('BTECH', 'BTech'), ('MTECH', 'MTech'), ('MSC', 'MSc')], default='BTECH', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, max_length=5000, null=True)),
                ('perks', models.TextField(blank=True, max_length=5000, null=True)),
                ('infra_req', models.TextField(blank=True, max_length=5000, null=True)),
                ('other', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='CRPDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype', models.CharField(choices=[('MON', 'Month'), ('WOM', 'Week of Month'), ('DAT', 'Date')], max_length=3)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('week_number', models.CharField(blank=True, choices=[('F', 'First'), ('S', 'Second'), ('T', 'Third'), ('L', 'Last')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('requirements', models.TextField(blank=True, max_length=5000, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, max_length=5000, null=True)),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('ctc_details', models.TextField(blank=True, max_length=5000, null=True)),
                ('bond_details', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('number_of_selections', models.IntegerField(blank=True, null=True)),
                ('other', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_location', to='company.Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_domain', models.CharField(choices=[('C', 'Core'), ('N', 'Non-Core')], max_length=1)),
                ('job_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ctc_range', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='jobtype',
            unique_together=set([('job_domain', 'job_type')]),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='company.PlacementCategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='company.Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_branches',
            field=models.ManyToManyField(to='company.Branch'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='company.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='selection_procedure',
            field=models.ManyToManyField(to='company.SelectionProcedure'),
        ),
        migrations.AddField(
            model_name='crpdate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crpdate', to='company.Job'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set([('name', 'degree')]),
        ),
        migrations.AddField(
            model_name='attachment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='company.Job'),
        ),
        migrations.AlterUniqueTogether(
            name='joblocation',
            unique_together=set([('job', 'location')]),
        ),
    ]
