# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0004_auto_20170207_1434'),
        ('company', '0004_auto_20170204_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_data_fields',
            field=models.ManyToManyField(to='consent.UserDataFields'),
        ),
    ]
