# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20170208_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
