# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20170211_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='selection_procedure',
            field=models.ManyToManyField(blank=True, to='company.SelectionProcedure'),
        ),
    ]
