# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20170214_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['degree']},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='readable_degree',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='readable_name',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('CO', 'Computer Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('CH', 'Chemical Engineering'), ('EC', 'Electronics Engineering'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematics'), ('ALL', 'All Branches')], max_length=4),
        ),
    ]
