# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20170214_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
