# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20170409_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resumes_required',
            field=models.BooleanField(default=False),
        ),
    ]
