# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20170530_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ctc_unit',
            field=models.CharField(choices=[('LPA', 'lpa'), ('PM', 'pm'), ('PA', 'pa')], default='LPA', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='for_batch',
            field=models.CharField(default='2018', max_length=4),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_for',
            field=models.CharField(choices=[('FT', 'Full Time'), ('IN', 'Internship')], default='FT', max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
