# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0018_auto_20170616_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
