# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetail',
            name='hsc_passing_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
