# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0006_fieldorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatafields',
            name='default_position',
            field=models.IntegerField(default=0),
        ),
    ]
