# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0007_userdatafields_default_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldorder',
            name='optional',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
