# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0008_fieldorder_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='hometown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
