# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0009_personaldetail_hometown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationdetail',
            old_name='extrance_exam_score',
            new_name='entrance_exam_score',
        ),
    ]
