# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0010_auto_20170214_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetail',
            old_name='premanent_address',
            new_name='permanent_address',
        ),
    ]
