# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0014_auto_20170325_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconsent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
