# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0015_auto_20170403_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='entrance_exam',
            field=models.CharField(choices=[('JEE_MAIN', 'JEE Mains'), ('SAT', 'SAT')], default='JEE_MAIN', max_length=8),
        ),
    ]
