# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0016_auto_20170416_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='current_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
