# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0018_auto_20170416_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgpa',
            name='semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth'), ('9', 'Ninth'), ('10', 'Tenth')], max_length=2),
        ),
    ]
