# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 10:45
from __future__ import unicode_literals

from django.db import migrations


def load_user_data_fields(apps, schema_editor):
	UserDataFields =  apps.get_model('consent', 'UserDataFields')
	
	UserDataFields(name='Roll Number', slug='roll_number', default_position=1).save()
	UserDataFields(name='Name', slug='name', default_position=2).save()
	UserDataFields(name='Date of Birth', slug='date_of_birth', default_position=3).save()
	UserDataFields(name='Caste Category', slug='caste_category', default_position=4).save()
	UserDataFields(name='Hometown', slug='hometown', default_position=5).save()
	UserDataFields(name='Aggregate SSC %', slug='ssc', default_position=6).save()
	UserDataFields(name='Aggregate HSC %', slug='hsc', default_position=7).save()
	UserDataFields(name='CGPA Upto Semester', slug='cgpa_upto_semester', default_position=8).save()
	UserDataFields(name='Email ID', slug='email', default_position=9).save()
	UserDataFields(name='Phone Number', slug='phone_number', default_position=10).save()
	UserDataFields(name='SSC Passing Year', slug='ssc_passing_year', default_position=0).save()
	UserDataFields(name='HSC Passing Year', slug='hsc_passing_year', default_position=0).save()
	UserDataFields(name='Entrance Exam', slug='entrance_exam', default_position=0).save()
	UserDataFields(name='Entrance Exam Score', slug='entrance_exam_score', default_position=0).save()
	UserDataFields(name='Branch', slug='branch', default_position=0).save()
	UserDataFields(name='Current Backlogs', slug='current_backlogs', default_position=0).save()
	UserDataFields(name='Total Backlogs', slug='total_backlogs', default_position=0).save()
	UserDataFields(name='Current Address', slug='current_address', default_position=0).save()
	UserDataFields(name='Permanent Address', slug='permanent_address', default_position=0).save()
	UserDataFields(name='Current City', slug='current_city', default_position=0).save()
	UserDataFields(name='Permanent City', slug='permanent_city', default_position=0).save()
	UserDataFields(name='Current State', slug='current_state', default_position=0).save()
	UserDataFields(name='Permanent State', slug='permanent_state', default_position=0).save()
	UserDataFields(name='Current Address Pincode', slug='current_pincode', default_position=0).save()
	UserDataFields(name='Permanent Address Pincode', slug='permanent_pincode', default_position=0).save()
	UserDataFields(name='CGPA Of Semester', slug='cgpa_of_semester', default_position=0).save()


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0019_auto_20170520_1850'),
    ]

    operations = [
    	migrations.RunPython(load_user_data_fields),
    ]
