# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 11:38
from __future__ import unicode_literals

import consent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0020_auto_20170530_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=consent.models.OverwriteStorage(), upload_to=consent.models.resume_file_path),
        ),
    ]
